name: Deploy Vite React app to GitHub Pages

on:
  push:
    branches: [ "main" ]   # chạy khi bạn push lên main
  workflow_dispatch:        # cho phép chạy thủ công nếu cần

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22  # đúng version Node bạn đang dùng

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
